// ---------------------------------------------------------------------------
// AI content-generation pipeline.
//
// Replaces a course's placeholder notes + assessments with REAL, tool-specific
// content generated by Claude — one topic at a time, validated, then written
// to the database inside a transaction. Idempotent per topic and resumable:
// re-running regenerates; interrupting leaves completed topics intact.
//
//   Real mode  — set ANTHROPIC_API_KEY in .env, then:
//       GEN_LIMIT=5 node prisma/generate-content.js
//     (optionally GEN_SLUG=autocad to target one course)
//
//   Mock mode  — no API key: writes structured, tool-aware content so the
//     pipeline is demonstrable offline. Swap in a key for real prose.
//
// Cost/time warning: real mode calls the API once per topic (10 per course).
// Generating all 200+ courses is ~2,000+ calls — run in batches.
// ---------------------------------------------------------------------------

import "dotenv/config";
import { prisma } from "../src/lib/prisma.js";
import { MODULE_THEMES } from "./seed-content.js";

const API_KEY = process.env.ANTHROPIC_API_KEY || "";
const MODEL = process.env.GEN_MODEL || "claude-sonnet-5";
const GEN_LIMIT = Number(process.env.GEN_LIMIT || 3);
const GEN_SLUG = process.env.GEN_SLUG || "";
const NOTES_PER_TOPIC = 15;
const QUESTIONS = 10;

// ---- Generation backends ---------------------------------------------------

// Real backend: ask Claude for a full topic (notes + assessment) as JSON.
async function generateWithClaude(client, { tool, category, moduleTitle }) {
  const sys =
    "You are a senior engineering instructor writing professional course material. " +
    "Return ONLY valid JSON, no prose, no code fences.";
  const prompt = `Write study material for the course "${tool}" (category: ${category}), for the module "${moduleTitle}".
Return JSON with this exact shape:
{
  "notes": [ { "title": string, "contentMarkdown": string } ],   // exactly ${NOTES_PER_TOPIC} pages, each 150-300 words, real and specific to ${tool}
  "questions": [ { "prompt": string, "explanation": string,
    "choices": [ { "text": string, "isCorrect": boolean } ] } ]  // exactly ${QUESTIONS} questions, 4 choices each, exactly one correct
}
Make the notes genuinely about ${tool}: real concepts, workflows, menus/commands where relevant, and common mistakes. Questions must be answerable from the notes.`;

  const msg = await client.messages.create({
    model: MODEL,
    max_tokens: 8000,
    system: sys,
    messages: [{ role: "user", content: prompt }],
  });
  const text = msg.content.map((c) => (c.type === "text" ? c.text : "")).join("");
  return JSON.parse(stripFences(text));
}

// Mock backend: structured, tool-aware content (no API key needed).
function generateMock({ tool, category, moduleTitle, moduleNo }) {
  const notes = [];
  for (let p = 1; p <= NOTES_PER_TOPIC; p++) {
    notes.push({
      title: `${moduleTitle}: Section ${moduleNo}.${p}`,
      contentMarkdown:
        `# ${moduleTitle}\n\n_[MOCK-GENERATED] ${tool} — ${category} — page ${p}/${NOTES_PER_TOPIC}._\n\n` +
        `This page was produced by the content pipeline in **mock mode**. With an ` +
        `ANTHROPIC_API_KEY set, it would contain real, ${tool}-specific prose for ` +
        `section ${moduleNo}.${p}.\n\n> Reviewer flag: cite a source for every non-default input.\n`,
    });
  }
  const questions = [];
  for (let q = 1; q <= QUESTIONS; q++) {
    const correct = (moduleNo + q) % 4;
    questions.push({
      prompt: `[MOCK] Q${q}: Which statement about ${moduleTitle} in ${tool} is correct?`,
      explanation: `[MOCK] Grounded in ${tool} module ${moduleNo}.`,
      choices: Array.from({ length: 4 }, (_, c) => ({
        text: c === correct ? `Correct answer (${tool})` : `Distractor ${c + 1}`,
        isCorrect: c === correct,
      })),
    });
  }
  return { notes, questions };
}

function stripFences(s) {
  return s.replace(/^```(?:json)?/i, "").replace(/```$/i, "").trim();
}

// ---- Validation ------------------------------------------------------------
function validateTopic(data) {
  if (!data || !Array.isArray(data.notes) || !Array.isArray(data.questions)) return "missing notes/questions";
  if (data.notes.length < 1) return "no notes";
  for (const q of data.questions) {
    if (!Array.isArray(q.choices) || q.choices.length < 2) return "bad choices";
    if (q.choices.filter((c) => c.isCorrect).length !== 1) return "must have exactly one correct choice";
  }
  return null;
}

// ---- DB write --------------------------------------------------------------
async function writeTopic(topic, data) {
  await prisma.$transaction(async (tx) => {
    // Replace notes
    await tx.note.deleteMany({ where: { topicId: topic.id } });
    await tx.note.createMany({
      data: data.notes.map((n, i) => ({
        topicId: topic.id,
        pageNumber: i + 1,
        title: (n.title || `Page ${i + 1}`).slice(0, 200),
        contentMarkdown: n.contentMarkdown || "",
      })),
    });

    // Replace assessment (delete cascades to questions/choices)
    if (topic.assessment) {
      await tx.selfAssessment.delete({ where: { id: topic.assessment.id } });
    }
    await tx.selfAssessment.create({
      data: {
        topicId: topic.id,
        title: `Self-Assessment: ${topic.title}`,
        questions: {
          create: data.questions.map((q, qi) => ({
            order: qi + 1,
            prompt: q.prompt,
            explanation: q.explanation || null,
            choices: {
              create: q.choices.map((c, ci) => ({
                order: ci + 1,
                text: c.text,
                isCorrect: Boolean(c.isCorrect),
              })),
            },
          })),
        },
      },
    });
  });
}

// ---- Orchestration ---------------------------------------------------------
async function main() {
  const mock = !API_KEY;
  console.log(mock ? "Running in MOCK mode (no ANTHROPIC_API_KEY set)." : `Running with Claude (${MODEL}).`);

  let client = null;
  if (!mock) {
    const { default: Anthropic } = await import("@anthropic-ai/sdk");
    client = new Anthropic({ apiKey: API_KEY });
  }

  const courses = await prisma.course.findMany({
    where: {
      isPlaceholder: true, // never overwrite real courses (e.g. PVsyst)
      ...(GEN_SLUG ? { slug: GEN_SLUG } : {}),
    },
    orderBy: { title: "asc" },
    take: GEN_LIMIT,
    select: {
      id: true,
      slug: true,
      title: true,
      category: true,
      topics: {
        orderBy: { order: "asc" },
        select: { id: true, order: true, title: true, assessment: { select: { id: true } } },
      },
    },
  });

  console.log(`Generating content for ${courses.length} course(s)...`);
  let topicsDone = 0;

  for (const course of courses) {
    console.log(`\n• ${course.title} (${course.topics.length} topics)`);
    for (const topic of course.topics) {
      const theme = MODULE_THEMES[(topic.order - 1) % MODULE_THEMES.length];
      const ctx = {
        tool: course.title,
        category: course.category || "Engineering",
        moduleTitle: topic.title,
        moduleNo: topic.order,
      };
      try {
        const data = mock ? generateMock(ctx) : await generateWithClaude(client, ctx);
        const err = validateTopic(data);
        if (err) {
          console.log(`   ! topic ${topic.order} skipped: ${err}`);
          continue;
        }
        await writeTopic(topic, data);
        topicsDone += 1;
        console.log(`   ✓ topic ${topic.order}: ${data.notes.length} notes, ${data.questions.length} questions`);
      } catch (e) {
        console.log(`   ! topic ${topic.order} failed: ${e.message}`);
      }
    }
    // Mark the course as no longer placeholder once generated.
    await prisma.course.update({ where: { id: course.id }, data: { isPlaceholder: mock } });
  }

  console.log(`\n✔ Done. ${topicsDone} topics written${mock ? " (mock)" : ""}.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
