import { prisma } from "../lib/prisma.js";

// Loads a course with all topics + note pages in order. Shared by the
// Markdown and PDF exporters and by the on-screen reader.
export async function loadCourseNotes(slug) {
  return prisma.course.findUnique({
    where: { slug },
    select: {
      id: true,
      slug: true,
      title: true,
      summary: true,
      level: true,
      category: true,
      isPlaceholder: true,
      discipline: { select: { name: true } },
      topics: {
        orderBy: { order: "asc" },
        select: {
          order: true,
          title: true,
          notes: {
            orderBy: { pageNumber: "asc" },
            select: { pageNumber: true, title: true, contentMarkdown: true },
          },
        },
      },
    },
  });
}

// Loads a course's outline: every part with its note/lab counts and whether
// it is assessed. Used for the outline view and the outline PDF.
export async function loadCourseOutline(slug) {
  return prisma.course.findUnique({
    where: { slug },
    select: {
      id: true, slug: true, title: true, summary: true, level: true, category: true,
      discipline: { select: { name: true } },
      topics: {
        orderBy: { order: "asc" },
        select: {
          order: true, title: true,
          _count: { select: { notes: true, labs: true } },
          assessment: { select: { id: true } },
        },
      },
    },
  });
}

// Loads a single topic (by course slug + 1-based order) with its notes + labs,
// for the per-topic PDF exports.
export async function loadCourseTopic(slug, order) {
  const course = await prisma.course.findUnique({
    where: { slug },
    select: { id: true, slug: true, title: true, discipline: { select: { name: true } } },
  });
  if (!course) return null;
  const topic = await prisma.topic.findFirst({
    where: { courseId: course.id, order },
    select: {
      order: true,
      title: true,
      notes: { orderBy: { pageNumber: "asc" }, select: { pageNumber: true, title: true, contentMarkdown: true } },
      labs: { orderBy: { order: "asc" }, select: { order: true, title: true, objective: true, instructionsMarkdown: true, estimatedMinutes: true } },
    },
  });
  if (!topic) return null;
  return { course, topic };
}

// Compiles the whole course into a single Markdown document (cover + contents
// + every topic's note pages) that a learner can download and keep.
export function buildNotesMarkdown(course) {
  const lines = [];
  lines.push(`# ${course.title} — Study Notes`);
  lines.push("");
  lines.push(`**Department:** ${course.discipline?.name || "—"}  `);
  if (course.category) lines.push(`**Category:** ${course.category}  `);
  lines.push(`**Level:** ${course.level}  `);
  lines.push("");
  lines.push(`> ${course.summary}`);
  lines.push("");
  if (course.isPlaceholder) {
    lines.push("> _Note: this course uses structured placeholder content for demonstration._");
    lines.push("");
  }
  lines.push("---");
  lines.push("");

  // Contents
  lines.push("## Contents");
  lines.push("");
  for (const t of course.topics) {
    lines.push(`${t.order}. ${t.title}`);
  }
  lines.push("");
  lines.push("---");
  lines.push("");

  // Body
  for (const t of course.topics) {
    lines.push(`# ${t.title}`);
    lines.push("");
    for (const n of t.notes) {
      lines.push(`## ${t.order}.${n.pageNumber} — ${n.title}`);
      lines.push("");
      lines.push(n.contentMarkdown.trim());
      lines.push("");
    }
    lines.push("---");
    lines.push("");
  }

  lines.push(`_Generated by Mentora — ${course.topics.length} modules._`);
  return lines.join("\n");
}

// Safe ASCII filename base for downloads.
export function notesFilenameBase(course) {
  return course.slug.replace(/[^a-z0-9-]/gi, "-");
}
